import { ContentItem, Platform, DailyStat, Topic } from "../types/dashboard-types";

export const DAILY_STATS: DailyStat[] = [
  { date: 'Jan 4', twitter: 2000, linkedin: 1000, youtube: 500 },
  { date: 'Jan 7', twitter: 15000, linkedin: 8000, youtube: 2500 },
  { date: 'Jan 10', twitter: 45000, linkedin: 12000, youtube: 4000 },
  { date: 'Jan 13', twitter: 85000, linkedin: 35000, youtube: 8000 },
  { date: 'Jan 16', twitter: 142000, linkedin: 58000, youtube: 15000 },
  { date: 'Jan 21', twitter: 185000, linkedin: 72000, youtube: 28000 },
  { date: 'Jan 28', twitter: 215000, linkedin: 95000, youtube: 40000 },
];

export const MOCK_POSTS: ContentItem[] = [
  {
    id: '1',
    platform: Platform.TWITTER,
    snippet: 'Why the "Full Service" agency model is dying in 2025.',
    fullContent: 'Why the "Full Service" agency model is dying in 2025. Clients no longer want generalists; they want specialized partners who understand their niche inside out. The rise of fractional talent and AI-driven automation is making bloated agency teams obsolete. Adapt or be left behind.',
    date: 'Oct 28',
    topic: 'Agency',
    likes: 1240,
    comments: 85,
    impressions: 45000,
    engagementRate: 3.5,
    viralityScore: 88,
    grade: 'A',
    url: 'https://x.com'
  },
  {
    id: '2',
    platform: Platform.LINKEDIN,
    snippet: 'The ROI of personal branding is hidden in your DMs.',
    fullContent: 'The ROI of personal branding is hidden in your DMs. Most people look at likes and shares, but the real business happens in private messages. That high-value prospect who never liked your post but sent you a "Hey, let\'s talk" message? That\'s the real win. Content is the magnet, DMs are the closing room.',
    date: 'Oct 27',
    topic: 'Branding',
    likes: 4500,
    comments: 320,
    impressions: 120000,
    engagementRate: 5.2,
    viralityScore: 96,
    grade: 'S',
    url: 'https://linkedin.com'
  },
  {
    id: '3',
    platform: Platform.TWITTER,
    snippet: 'Unpopular opinion: AI agents won\'t replace workers.',
    fullContent: 'Unpopular opinion: AI agents won\'t replace workers. They will replace the workers who refuse to use them. We are entering an era of "Super-Collaborators" where one person + five AI agents can do the work of a 10-person department. It\'s not about job loss; it\'s about task evolution.',
    date: 'Oct 25',
    topic: 'AI Agents',
    likes: 450,
    comments: 110,
    impressions: 15000,
    engagementRate: 2.1,
    viralityScore: 42,
    grade: 'C',
    url: 'https://x.com'
  },
  {
    id: '4',
    platform: Platform.LINKEDIN,
    snippet: 'How we scaled our SaaS from $0 to $10k MRR in 4 months.',
    fullContent: 'How we scaled our SaaS from $0 to $10k MRR in 4 months. We did three things: 1. Talked to 100 users before writing a single line of code. 2. Focused on a single burning pain point. 3. Leveraged programmatic SEO to drive 10k monthly organic visitors. Scale isn\'t a secret; it\'s a system.',
    date: 'Oct 23',
    topic: 'SaaS',
    likes: 2100,
    comments: 145,
    impressions: 80000,
    engagementRate: 4.0,
    viralityScore: 75,
    grade: 'B',
    url: 'https://linkedin.com'
  },
  {
    id: '5',
    platform: Platform.TWITTER,
    snippet: 'The secret to 10k followers isn\'t "quality" content.',
    fullContent: 'The secret to 10k followers isn\'t "quality" content. It\'s "relevant" content delivered with "consistency". Quality is subjective. Relevance to your target audience is objective. If you solve their problems every day for 365 days, growth becomes inevitable.',
    date: 'Oct 22',
    topic: 'Growth',
    likes: 890,
    comments: 42,
    impressions: 32000,
    engagementRate: 3.1,
    viralityScore: 68,
    grade: 'B',
    url: 'https://x.com'
  },
  {
    id: '6',
    platform: Platform.LINKEDIN,
    snippet: 'Stop hiring for "culture fit". Hire for "culture add".',
    fullContent: 'Stop hiring for "culture fit". Hire for "culture add". "Fit" often leads to bias and echo chambers. "Add" brings in diverse perspectives that challenge the status quo and drive innovation. Your company culture should be a living organism that evolves with every new hire.',
    date: 'Oct 21',
    topic: 'Hiring',
    likes: 3200,
    comments: 190,
    impressions: 95000,
    engagementRate: 4.5,
    viralityScore: 82,
    grade: 'A',
    url: 'https://linkedin.com'
  },
  {
    id: '7',
    platform: Platform.TWITTER,
    snippet: 'Most "AI Startups" are just wrappers. Here\'s why.',
    fullContent: 'Most "AI Startups" are just wrappers. They are building on shaky ground by relying solely on third-party APIs with zero proprietary data or workflows. The winners will be those who integrate AI into deep, specialized enterprise processes where the "moat" is the data, not the LLM.',
    date: 'Oct 20',
    topic: 'AI Agents',
    likes: 1560,
    comments: 210,
    impressions: 55000,
    engagementRate: 4.2,
    viralityScore: 91,
    grade: 'A',
    url: 'https://x.com'
  },
  {
    id: '8',
    platform: Platform.LINKEDIN,
    snippet: 'The 4-hour work week is a myth for founders.',
    fullContent: 'The 4-hour work week is a myth for founders. Building something meaningful requires obsession. You can\'t "hack" your way to a billion-dollar company in 4 hours a week. What you can do is find work that feels like play, so the 80 hours a week don\'t feel like a chore.',
    date: 'Oct 19',
    topic: 'Founders',
    likes: 1200,
    comments: 88,
    impressions: 40000,
    engagementRate: 3.2,
    viralityScore: 60,
    grade: 'B',
    url: 'https://linkedin.com'
  },
  {
    id: '9',
    platform: Platform.TWITTER,
    snippet: 'If you aren\'t using Cursor yet, you are falling behind.',
    fullContent: 'If you aren\'t using Cursor yet, you are falling behind. AI-native IDEs are not just "autocomplete". They are junior developers that understand your entire codebase. I built a full-stack feature in 20 minutes today that would have taken 4 hours last month. The bar for productivity just went up.',
    date: 'Oct 18',
    topic: 'AI Agents',
    likes: 2300,
    comments: 145,
    impressions: 68000,
    engagementRate: 5.1,
    viralityScore: 94,
    grade: 'S',
    url: 'https://x.com'
  },
  {
    id: '10',
    platform: Platform.LINKEDIN,
    snippet: '3 lessons I learned from losing my biggest client.',
    fullContent: '3 lessons I learned from losing my biggest client. 1. Never let one client represent more than 20% of your revenue. 2. Always be selling, even when you are fully booked. 3. Contractual churn is part of the game; emotional churn is optional. Resilience is the only path forward.',
    date: 'Oct 17',
    topic: 'Agency',
    likes: 980,
    comments: 112,
    impressions: 35000,
    engagementRate: 3.8,
    viralityScore: 65,
    grade: 'B',
    url: 'https://linkedin.com'
  },
];

export const TOPICS: Topic[] = [
  { name: 'AI Agents', score: 92, volume: 80, sentiment: 'positive' },
  { name: 'SaaS Growth', score: 85, volume: 60, sentiment: 'positive' },
  { name: 'Cold Email', score: 45, volume: 40, sentiment: 'negative' },
  { name: 'Personal Branding', score: 78, volume: 70, sentiment: 'neutral' },
  { name: 'No-Code Tools', score: 65, volume: 50, sentiment: 'positive' },
  { name: 'Founder Health', score: 30, volume: 20, sentiment: 'neutral' },
];